var github = require('octonode');

// list all the repos
export async function GET(request: Request) {
  const client = github.client(process.env.GITHUB_TOKEN);
  const ghme = client.me();
  const response = await ghme.reposAsync();
  // console.log(response[0]);
  return new Response(JSON.stringify(response[0]));
}

/** @typedef {Object} Repo
 *   {
    id: 483294188,
    node_id: 'R_kgDOHM577A',
    name: 'wallpapers',
    full_name: 'kanopo/wallpapers',
    private: false,
    owner: {
      login: 'kanopo',
      id: 64138187,
      node_id: 'MDQ6VXNlcjY0MTM4MTg3',
      avatar_url: 'https://avatars.githubusercontent.com/u/64138187?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/kanopo',
      html_url: 'https://github.com/kanopo',
      followers_url: 'https://api.github.com/users/kanopo/followers',
      following_url: 'https://api.github.com/users/kanopo/following{/other_user}',
      gists_url: 'https://api.github.com/users/kanopo/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/kanopo/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/kanopo/subscriptions',
      organizations_url: 'https://api.github.com/users/kanopo/orgs',
      repos_url: 'https://api.github.com/users/kanopo/repos',
      events_url: 'https://api.github.com/users/kanopo/events{/privacy}',
      received_events_url: 'https://api.github.com/users/kanopo/received_events',
      type: 'User',
      site_admin: false
    },
    html_url: 'https://github.com/kanopo/wallpapers',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/kanopo/wallpapers',
    forks_url: 'https://api.github.com/repos/kanopo/wallpapers/forks',
    keys_url: 'https://api.github.com/repos/kanopo/wallpapers/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/kanopo/wallpapers/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/kanopo/wallpapers/teams',
    hooks_url: 'https://api.github.com/repos/kanopo/wallpapers/hooks',
    issue_events_url: 'https://api.github.com/repos/kanopo/wallpapers/issues/events{/number}',
    events_url: 'https://api.github.com/repos/kanopo/wallpapers/events',
    assignees_url: 'https://api.github.com/repos/kanopo/wallpapers/assignees{/user}',
    branches_url: 'https://api.github.com/repos/kanopo/wallpapers/branches{/branch}',
    tags_url: 'https://api.github.com/repos/kanopo/wallpapers/tags',
    blobs_url: 'https://api.github.com/repos/kanopo/wallpapers/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/kanopo/wallpapers/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/kanopo/wallpapers/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/kanopo/wallpapers/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/kanopo/wallpapers/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/kanopo/wallpapers/languages',
    stargazers_url: 'https://api.github.com/repos/kanopo/wallpapers/stargazers',
    contributors_url: 'https://api.github.com/repos/kanopo/wallpapers/contributors',
    subscribers_url: 'https://api.github.com/repos/kanopo/wallpapers/subscribers',
    subscription_url: 'https://api.github.com/repos/kanopo/wallpapers/subscription',
    commits_url: 'https://api.github.com/repos/kanopo/wallpapers/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/kanopo/wallpapers/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/kanopo/wallpapers/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/kanopo/wallpapers/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/kanopo/wallpapers/contents/{+path}',
    compare_url: 'https://api.github.com/repos/kanopo/wallpapers/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/kanopo/wallpapers/merges',
    archive_url: 'https://api.github.com/repos/kanopo/wallpapers/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/kanopo/wallpapers/downloads',
    issues_url: 'https://api.github.com/repos/kanopo/wallpapers/issues{/number}',
    pulls_url: 'https://api.github.com/repos/kanopo/wallpapers/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/kanopo/wallpapers/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/kanopo/wallpapers/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/kanopo/wallpapers/labels{/name}',
    releases_url: 'https://api.github.com/repos/kanopo/wallpapers/releases{/id}',
    deployments_url: 'https://api.github.com/repos/kanopo/wallpapers/deployments',
    created_at: '2022-04-19T15:02:44Z',
    updated_at: '2022-08-17T11:20:54Z',
    pushed_at: '2023-03-07T15:12:30Z',
    git_url: 'git://github.com/kanopo/wallpapers.git',
    ssh_url: 'git@github.com:kanopo/wallpapers.git',
    clone_url: 'https://github.com/kanopo/wallpapers.git',
    svn_url: 'https://github.com/kanopo/wallpapers',
    homepage: null,
    size: 83758,
    stargazers_count: 0,
    watchers_count: 0,
    language: null,
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
    permissions: {
      admin: true,
      maintain: true,
      push: true,
      triage: true,
      pull: true
    }
  }

  */